# Columns for the tabular data, ordered by how they were used in the model.
TABULAR_DATA_COLUMNS = ['patient_age', 'cci_age_score', 'myocardial_infarct',
       'congestive_heart_failure', 'peripheral_vascular_disease',
       'cerebrovascular_disease', 'dementia', 'chronic_pulmonary_disease',
       'rheumatic_disease', 'peptic_ulcer_disease', 'mild_liver_disease',
       'diabetes_without_cc', 'diabetes_with_cc', 'paraplegia',
       'renal_disease', 'malignant_cancer', 'severe_liver_disease',
       'metastatic_solid_tumor', 'aids', 'charlson_comorbidity_index',
       'heart_rate_min', 'heart_rate_max', 'heart_rate_mean', 'sbp_min',
       'sbp_max', 'sbp_mean', 'dbp_min', 'dbp_max', 'dbp_mean', 'mbp_min',
       'mbp_max', 'mbp_mean', 'resp_rate_min', 'resp_rate_max',
       'resp_rate_mean', 'temperature_min', 'temperature_max',
       'temperature_mean', 'spo2_min', 'spo2_max', 'spo2_mean', 'glucose_min',
       'glucose_max', 'glucose_mean', 'hematocrit_min', 'hematocrit_max',
       'hemoglobin_min', 'hemoglobin_max', 'platelets_min', 'platelets_max',
       'wbc_min', 'wbc_max', 'aniongap_min', 'aniongap_max', 'bicarbonate_min',
       'bicarbonate_max', 'bun_min', 'bun_max', 'calcium_min', 'calcium_max',
       'chloride_min', 'chloride_max', 'creatinine_min', 'creatinine_max',
       'glucose_min_1', 'glucose_max_1', 'sodium_min', 'sodium_max',
       'potassium_min', 'potassium_max', 'inr_min', 'inr_max', 'pt_min',
       'pt_max', 'ptt_min', 'ptt_max', 'gender_F']